version: '3.8'

services:
  web:
    build: .
    command: poetry run python ./app/web.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env_file
  db:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ai_db_user
      - POSTGRES_PASSWORD=os.getenv('SQL_PASSWORD')
      - POSTGRES_DB=os.getenv('SQL_DB')
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: