version: '3.8'

services:
  web:
    build: .
    command: make run_web
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - web:/web
    env_file:
      - ./.env
  db:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  web: