name: Code checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target: [pylint, flake8]
    steps:
      - uses: actions/checkout@v3
      - name: Install Python3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install requirements
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check ${{ matrix.build_target }}
        run: ${{ matrix.build_target }} app/ handwritten_text_recognition_model/