name: Code checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target: [pylint, flake8]
    steps:
      - uses: actions/checkout@v3
      - name: Install Python3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Add Poetry to $PATH
        run: export poetry=~/.local/share/pypoetry/venv/bin/poetry
      - name: Install dependencies
        run: poetry lock --no-update && poetry install
      - name: Check ${{ matrix.build_target }}
        run: poetry run ${{ matrix.build_target }} .